apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "zookeeper.fullname" . }}
  labels:
    app: {{ template "zookeeper.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  zoo.cfg: |-
    tickTime=2000
    initLimit=10
    syncLimit=5
    dataDir=/data/zookeeper
    clientPort=2181
    # {{ .Values.replicaCount }}
    {{ if eq ".Values.replicaCount)" "3" }}
    server.1={{ template "zookeeper.fullname" . }}-0.{{ template "zookeeper.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:2888:3888
    server.2={{ template "zookeeper.fullname" . }}-1.{{ template "zookeeper.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:2888:3888
    server.3={{ template "zookeeper.fullname" . }}-2.{{ template "zookeeper.fullname" . }}-headless.{{ .Release.Namespace }}.svc.{{ .Values.clusterDomain }}:2888:3888
    {{ end }}
